version: '3.7'

services:
    app: #defines the app container
        build:
            context: .  #uses the Dockerfile found in current folder
            command : ["./wait-for-it.sh" , "db:3306" , "--strict" , "--timeout=300" , "--" , "npm","start"]

        ports: #need to setup port mapping
            - "8080:3000" 
       
            
        env_file: .env
        
        depends_on: #we need the database server for this container to be functional
            - db
        

    db:
        image: mysql:5.7 #we are getting this from a pre-built image
        volumes: 
        - ./data:/var/lib/mysql
        environment: #set the environment variables as per instructions on docker hub
            MYSQL_ROOT_PASSWORD: "123"
            MYSQL_USER: ${DATABASE_USER} 
            MYSQL_PASSWORD: ${DATABASE_PASSWORD} 
            MYSQL_DATABASE: ${DATABASE_NAME} 
        ports: #need to be able to connect to the db as well
            - "8080:3000"

            
         